# launch apps
bind = super, t, exec, konsole
bind = super, b, exec, firefox
bind = super, r, exec, killall wofi || wofi -aIi -S drun 

# screenshot
bind = shift ,Print, exec, pgrep slurp || grim
bind = ,Print, exec, pgrep slurp || grim -g "$(slurp)" 
bind = alt ,Print, exec, pgrep slurp || grim -g "$(slurp)" - | wl-copy

# fn keys
binde=, XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel=, XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel=, XF86MonBrightnessDown, exec, brightnessctl set 5%- -n
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioPrev, exec, playerctl previous
bindl = ,XF86AudioNext, exec, playerctl next

# lock screen
bind = super, l, exec, swaylock -eF -i /usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg
bindl= ,switch:Lid Switch, exec, swaylock -eF -i /usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg

