$lock = swaylock -eF -i /usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg

exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = nm-applet
exec-once = waybar
exec-once = wlsunset -T 4000 -t 3500

windowrulev2 = suppressevent maximize, class:.* 
windowrulev2 = workspace 1, class:^org\.kde\.konsole$, title:^\~\ \:\ bash\ \—\ Konsole$
windowrulev2 = workspace 2, class:^org\.mozilla\.firefox, title:^Mozilla\ Firefox$
# windowrulev3 = workspace 3, class:

bind = super, t, exec, konsole
bind = super, b, exec, firefox
bind = super, r, exec, wofi -IS drun 

bind = shift ,Print, exec, grim
bind = ,Print, exec, grim -g "$(slurp)" 

binde=, XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindel=, XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel=, XF86MonBrightnessDown, exec, brightnessctl set 5%- -n

bind = super, l, exec, $lock
bindl= ,switch:Lid Switch, exec, $lock

