# do not allow windows to open maximized
windowrulev2 = suppressevent maximize, class:.* 

# smart gaps (disabled on special workspaces)
workspace = w[t1] s[false], gapsout:0
windowrulev2 = bordersize 0 , floating:0, onworkspace: w[t1] s[false]
windowrulev2 = rounding 0 , floating:0, onworkspace: w[t1] s[false]

# assign workspaces to apps (disabled on special workspaces)
windowrulev2 = workspace 1, class:^org\.kde\.konsole$, onworkspace: s[false]
windowrulev2 = workspace 2, class:^org\.mozilla\.firefox, onworkspace: s[false]
windowrulev2 = workspace 3, class:^org\.kde\.okular$, onworkspace: s[false]
windowrulev2 = workspace 4, class:^libreoffice.*$, onworkspace: s[false]
