# command to execute after launching Hyprland
exec-once = GTK_THEME=Adwaita waybar
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = gsettings set org.gnome.desktop.interface cursor-theme breeze_cursor
exec-once = gsettings set org.gnome.desktop.interface gtk-theme Breeze
exec-once = pgrep gammastep || gammastep -O 4000

