# command to execute after launching Hyprland
exec-once = GTK_THEME=Adwaita waybar
exec-once = gammastep -O 4000

# command to run every time Hyprland is reloaded
exec = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec = gsettings set org.gnome.desktop.interface cursor-theme breeze_cursor
exec = gsettings set org.gnome.desktop.interface gtk-theme Breeze
