# global binds to enter submaps
bind = super, escape, exec,
bind = super, f1, submap, clean

# submap with no binds
submap = clean
bind = super, escape, submap, reset
bind = super, f1, exec,
submap = reset
