# global submap bindings
bind = super, escape, submap,  reset
bind = super, f1, submap,  clean
bind = super, f2, submap,  resize

# submap with no bindings
submap = clean
bind = super, escape, submap,  reset
bind = super, f1, submap,  clean
bind = super, f2, submap,  resize
submap = reset
