# global submap bindings
bind = super, escape, submap,  reset
bind = super, f1, exec
bind = super, f2, submap,  clean
bind = super, f3, submap,  resize

# submap with no bindings
submap = clean
bind = super, escape, submap,  reset
bind = super, f1, exec,
bind = super, f2, submap,  clean
bind = super, f3, submap,  resize
submap = reset

# submap for resizing windows
submap = resize
bind = super, escape, submap,  reset
bind = super, f1, exec,
bind = super, f2, submap,  clean
bind = super, f3, submap,  resize
binde= super shift, right, resizeactive, 10 0
binde= super shift, left, resizeactive, -10 0
binde= super shift, up, resizeactive, 0 -10
binde= super shift, down, resizeactive, 0 10
binde= super, right, moveactive, 10 0
binde= super, left, moveactive, -10 0
binde= super, up, moveactive, 0 -10
binde= super, down, moveactive, 0 10
bind= super, v, togglefloating
bind= super, c, centerwindow
submap = reset
