# global submap bindings
bind = super, escape, submap,  reset
bind = super ctrl, c, submap,  clean

# submap with no bindings
submap = clean
bind = super, escape, submap,  reset
bind = super ctrl, c, submap,  clean
submap = reset

