$terminal = konsole
$browser = firefox
$menu = wofi -S drun -I

$cmd_volinc = wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
$cmd_voldec = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
$cmd_voltog = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
$cmd_liginc = brightnessctl set +5%
$cmd_ligdec = brightnessctl set 5%- -n
$cmd_ligtog = killall wlsunset || wlsunset -T 4000 -t 3500

