#!/bin/python3

import os
import getopt
import sys
import itertools as itt
import subprocess as proc
import filecmp as cmp
from shutil import copyfile as cp

HOME = os.path.expanduser("~")
SCRIPT_PATH = os.path.realpath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
DIRS = {"backup": os.path.join(SCRIPT_DIR, "backup"),
        "config": os.path.join(SCRIPT_DIR, "config"),
        "init": os.path.join(SCRIPT_DIR, "init"),
        "bigfiles": os.path.join(SCRIPT_DIR, "bigfiles")}
FILES = {"track": os.path.join(DIRS["config"], "files_to_track.txt"),
         "track2": os.path.join(DIRS["config"], "files_to_track2.txt"),
         "skip": os.path.join(DIRS["config"], "files_to_skip.txt"),
         "skip2": os.path.join(DIRS["config"], "files_to_skip2.txt")}


# UTILITY FUNCTIONS
def color(clr, str, output=True):
    clr_str = "\033["
    match clr:
        case "err": clr_str += "1;31m"
        case "file": clr_str += "1;34m"
        case "msg": clr_str += "1;33m"
    res = clr_str + str + "\033[m"
    if output:
        print(res, end="")
    else:
        return res


def ask_user(msg, opts, clr=False):
    color("msg", msg) if clr else print(msg, end="")
    if 'n' in opts:
        print('n')
        return False
    if 'y' in opts:
        print("y")
        return True
    answer = input()
    if answer == "y":
        return True
    if answer == "n" or not answer.strip():
        return False
    print("Invalid answer, retry:")
    return ask_user(msg, opts, clr)


def all_files(dir, relpath=None):
    files = []
    for root, _, dirfiles in os.walk(dir):
        for f in dirfiles:
            fname = os.path.join(root, f)
            if os.path.isfile(fname):
                if relpath is None:
                    files.append(fname)
                else:
                    files.append(os.path.relpath(fname, relpath))
    return files


def load_config(conf):
    files = set()
    if os.path.isfile(conf):
        with open(conf, "r") as buffer:
            for line in buffer.read().splitlines():
                if not line.startswith("/") and line:
                    ofile = os.path.join(HOME, line)
                    bfile = os.path.join(DIRS["backup"], line)
                    if os.path.isfile(ofile):
                        files.add(line)
                    elif os.path.isdir(ofile):
                        files.update(all_files(ofile, HOME))
                    if os.path.isfile(bfile):
                        files.add(line)
                    elif os.path.isdir(bfile):
                        files.update(all_files(bfile, DIRS["backup"]))
    return files


def copy_file(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    cp(src, dst)


# ACTION FUNCTIONS
def backup(opts):
    backup = DIRS["backup"]
    msg1 = " : backup file is missing"
    msg2 = "Do you really want to create the backup file? "
    msg3 = "[DANGER] Do you really want to delete the original file? "
    msg4 = " : original file is missing"
    msg5 = "Do you really want to delete the backup file? "
    msg6 = "Do you really want to create the original file? "
    msg7 = " : original and backup files differ"
    msg8 = "Do you really want to update the backup file? "
    msg9 = "Do you really want to update the original file? "
    msg10 = " : file is untracked"
    msg11 = "[UNTRACKED] Do you really want to delete backup file? "
    msg12 = "[DANGER, UNTRACKED] Do you really want to delete original file? "

    # accumulate all tracked files
    tracked = load_config(FILES["track"])
    tracked2 = load_config(FILES["track2"])
    skipped = load_config(FILES["skip"])
    skipped2 = load_config(FILES["skip2"])
    tracked_unskipped = tracked - skipped
    tracked_unskipped2 = tracked2 - skipped2
    if intersection := tracked_unskipped & tracked_unskipped2:
        color("err", "ERROR: following files are in both tracking files:\n")
        for file in intersection:
            print(os.path.join(HOME, file))
        exit(1)
    files = sorted(tracked_unskipped2 if "t" in opts else tracked_unskipped)

    # backup action
    if "u" not in opts:
        if "t" in opts:
            color("msg", "WARNING: the secondary tracking list is in use!\n")
        for file in files:
            fhome = os.path.join(HOME, file)
            fback = os.path.join(backup, file)
            match os.path.isfile(fhome), os.path.isfile(fback):
                case True, False:
                    color("file", fhome)
                    print(msg1 if "v" in opts else "")
                    if "s" in opts and ask_user(msg2, opts, True):
                        copy_file(fhome, fback)
                    elif "b" in opts and "f" in opts:
                        if ask_user(msg3, opts, True):
                            os.remove(fhome)
                case False, True:
                    color("file", fhome)
                    print(msg4 if "v" in opts else "")
                    if "s" in opts and ask_user(msg5, opts, True):
                        os.remove(fback)
                    elif "b" in opts and ask_user(msg6, opts, True):
                        copy_file(fback, fhome)
                case True, True:
                    if not cmp.cmp(fhome, fback):
                        color("file", fhome)
                        print(msg7 if "v" in opts else "")
                        if "d" in opts:
                            if "b" in opts:
                                proc.run(
                                    ["diff", "--color", "-u", fhome, fback])
                            else:
                                proc.run(
                                    ["diff", "--color", "-u", fback, fhome])
                        if "s" in opts and ask_user(msg8, opts, True):
                            copy_file(fhome, fback)
                        elif "b" in opts and ask_user(msg9, opts, True):
                            copy_file(fback, fhome)

    # remove untracked files actions
    if "u" in opts:
        all_tracked = tracked_unskipped | tracked_unskipped2
        for file in sorted(set(all_files(backup, backup)) - all_tracked):
            fhome = os.path.join(HOME, file)
            fback = os.path.join(backup, file)
            color("file", fhome)
            print(msg10 if "v" in opts else "")
            if "t" in opts:
                if ask_user(msg11, opts, True):
                    os.remove(fback)
                if "f" in opts and ask_user(msg12, opts, True):
                    os.remove(fback)


def commit(opts):
    dir = SCRIPT_DIR
    msg1 = "Do you really want to commit all? "
    msg2 = "Do you really want to restore all? "

    # commit
    if "c" in opts:
        if proc.run(['git', '-C', dir, 'status', '-s'],
                    capture_output=True, text=True).stdout.strip():
            if "t" not in opts:
                proc.run(["git", "-C", dir, "pull"])
            if "d" in opts:
                if "t" not in opts:
                    proc.run(["git", "-C", dir, "--no-pager",
                             "diff", "HEAD", "--diff-filter=adcr"])
                if "t" in opts:
                    proc.run(["git", "-C", dir, "--no-pager",
                              "diff", "HEAD", "-R", "--diff-filter=adcr"])
            proc.run(["git", "-C", dir, "status", "-su"])
            if "t" not in opts and ask_user(msg1, opts, True):
                cmt = input(color("msg", "Write commit message: ", False))
                if cmt:
                    proc.run(["git", "-C", dir, "add", dir])
                    proc.run(["git", "-C", dir, "commit", "-m", cmt])
                    proc.run(["git", "-C", dir, "push"])
            elif "t" in opts and ask_user(msg2, opts, True):
                proc.run(["git", "-C", dir, "restore", "--staged", dir])
                proc.run(["git", "-C", dir, "restore", dir])
                proc.run(["git", "-C", dir, "clean", "-fdq"])


def help_msg():
    print("""  Flag options:
- d         diffs are shown
- f         forcely allow dangerous operations
- n         no is the default answer to all questions
- t         toggle secondary mode
- v         verbose output is shown
- y         yes is the default answer to all questions

  Action options:
- b         backup is restored
- c         pull,commit,push or restore
- e         edit config, init files
- h         help message is printed
- i         initialize necessary directories and files
- r         run init scripts
- s         save tracked files
- u         untracked files are shown and can be deleted

  Valid flag for each action:
-           d   n t v y
- b         d f n t v y
- c         d   n t   y
- e             n     y
- h
- i
- r             n     y
- s         d   n t v y
- u           f n t   y

  Shortcuts:
- save      -s -cvy
- restore   -b -vy
- init      -r -y
- edit      -e -y
- help      -h

  Environment
- __DBG   set to any not empty value, to allow print python stderr
- __CCK   set to any not empty value, to disable checking if flags are valid
            """)


def init_files():
    for dir in DIRS.values():
        if not os.path.exists(dir):
            os.makedirs(dir)
    for file in FILES.values():
        if not os.path.exists(file):
            open(file, 'w').close()


def edit(opts):
    for file in itt.chain([SCRIPT_PATH], FILES.values(),
                          all_files(DIRS["init"])):
        if os.path.exists(file):
            msg = color("msg", "Do you really want to edit ", False)
            msg += color("file", os.path.relpath(file, SCRIPT_DIR), False)
            msg += color("msg", " ? ", False)
            if ask_user(msg, opts):
                proc.run(["nvim", file])


def run(opts):
    for file in all_files(DIRS["init"]):
        msg = color("msg", "Do you really want to execute ", False)
        msg += color("file", os.path.relpath(file, SCRIPT_DIR), False)
        msg += color("msg", " ? ", False)
        if ask_user(msg, opts):
            os.chmod(file, os.stat(file).st_mode | 0o111)
            if proc.run(file).returncode != 0:
                color("err", "ERROR: init script failed!\n")
                exit(1)


# EXECUTION FUNCTIONS
def parse_options():
    args = sys.argv[1:]
    opts = set()

    # shortcuts
    if len(args) >= 1:
        match args[0]:
            case "save": opts = ['s', 'v', 'y']
            case "restore": opts = ['b', 'v', 'y']
            case "commit": opts = ['c', 'y']
            case "init": opts = ['r', 'y']
            case "edit": opts = ['e', 'y']
            case "help": opts = ['h']

    # parse options
    try:
        if not opts:
            args = [s for s in args if s.startswith("-")]
            opts = [c[1:] for c, _ in getopt.getopt(args, 'bcdefhinrstuvy')[0]]
        opts = set(opts)

        # parse action
        actions = set([opt for opt in opts if opt in 'bcehirsu'])
        num_act = len(actions)
        if num_act >= 2:
            color("err", "ERROR: too many action flags were passed:\n")
            for action in actions:
                print("-" + action, end=" ")
            print()
            exit(1)
        action = None if num_act == 0 else actions.pop()
        return opts, action
    except getopt.GetoptError as err:
        color("err", "ERROR: an invalid option was passed:\n")
        print(err)
        exit(1)


def check(opts, action):
    # check flags are valid for the current action
    all_valid_opts = {
        None: "dntvy",
        "b": "dfntvy",
        "c": "dnty",
        "e": "ny",
        "h": "",
        "i": "",
        "r": "ny",
        "s": "dntvy",
        "u": "fnty",
    }
    valid_opts = set(all_valid_opts[action])
    invalid_opts = opts - valid_opts - set([action])
    if invalid_opts:
        color("err", "ERROR: following flags are invalid for action '-")
        color("err", (action if action is not None else " ") + "' :\n")
        for flag in invalid_opts:
            print("-" + flag, end=" ")
        print()
        exit(1)

    # check there are no conflicting flags
    conflicting = [("n", "y")]
    for c1, c2 in conflicting:
        if c1 in opts and c2 in opts:
            color("err", "ERROR: following flags cannot be used togheter:\n")
            print("-" + c1 + " -" + c2)
            exit(1)


def execute(opts, action):
    match action:
        case "b" | "s" | None | "u": backup(opts)
        case "c": commit(opts)
        case "e": edit(opts)
        case "h": help_msg()
        case "i": init_files()
        case "r": run(opts)


# ACTUAL EXECUTION
if __name__ == "__main__":
    if not os.getenv("__DBG"):
        f = open(os.devnull, 'w')
        sys.stderr = f
    opts, action = parse_options()
    if not os.getenv("__CCK"):
        check(opts, action)
    execute(opts, action)
