# smart gaps 
workspace = w[t1] s[false], gapsout:0
windowrulev2 = bordersize 0 , floating:0, onworkspace: w[t1] s[false]
windowrulev2 = rounding 0 , floating:0, onworkspace: w[t1] s[false]

# various fixes
windowrulev2 = suppressevent maximize, class:.* 
windowrulev2 = rounding 0, xwayland:1

# assign workspaces to apps 
windowrulev2 = workspace 1, class:^org\.kde\.konsole$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 2, class:^org\.mozilla\.firefox$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 3, class:^org\.kde\.okular$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 11, class:^org\.kde\.konsole$, onworkspace: s[false] r[11-20]
windowrulev2 = workspace 12, class:^org\.mozilla\.firefox$, onworkspace: s[false] r[11-20]
windowrulev2 = workspace 13, class:^org\.kde\.okular$, onworkspace: s[false] r[11-20]


