# smart gaps 
workspace = w[t1], gapsout:0
windowrulev2 = bordersize 0 , floating:0, onworkspace: w[t1]
windowrulev2 = rounding 0 , floating:0, onworkspace: w[t1]

# various fixes
windowrulev2 = suppressevent maximize, class:.* 
windowrulev2 = rounding 0, xwayland:1

