source = include/variables.conf
source = include/configs.conf


#########################################################################################
#                                 DIRTY ZONE AFTER                                      #
#########################################################################################


monitor=,preferred,auto,1

exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = nm-applet
exec-once = waybar
exec-once = $cmd_ligtog

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,kde 
env = LANG,en_US.UTF-8
env = LC_ADDRESS,it_IT.UTF-8
env = LC_MEASUREMENT,it_IT.UTF-8
env = LC_MONETARY,it_IT.UTF-8
env = LC_NAME,it_IT.UTF-8
env = LC_NUMERIC,it_IT.UTF-8
env = LC_PAPER,it_IT.UTF-8
env = LC_TELEPHONE,it_IT.UTF-8
env = LC_TIME,en_GB.UTF-8

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Set programs that you use

# Some default env vars.


# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = workspace 1, class:^(org.kde.konsole)$
windowrulev2 = workspace 2, class:^(org.mozilla.firefox)$



# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = SUPER, T, exec, $terminal
bind = SUPER, B, exec, firefox
bind = SUPER, Q, killactive, 
bind = SUPER, M, exec, pkill -kill -u $USER
bind = SUPER, V, togglefloating, 
bind = SUPER, R, exec, $menu
bind = SUPER, P, pseudo, # dwindle
bind = SUPER, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = SUPER, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bindel=, XF86AudioRaiseVolume, exec, $cmd_volinc
bindel=, XF86AudioLowerVolume, exec, $cmd_voldec
bindel=, XF86AudioMute, exec, $cmd_voltog

bindel=, XF86MonBrightnessUp, exec, $cmd_liginc
bindel=, XF86MonBrightnessDown, exec, $cmd_ligdec



