$red = rgb(ed8796)
$yellow = rgb(eed49f)
$tealAlpha = 8bd5ca
$text = rgb(cad3f5)
$textAlpha = cad3f5
$surface0 = rgb(363a4f)
$base = rgb(24273a)
$accent = 0xb3$tealAlpha
$accentAlpha = $tealAlpha
$font = <none>

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

# BACKGROUND
background {
    monitor =
    path = /usr/share/wallpapers/Path/contents/images/1920x1080.jpg
    blur_passes = 0
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $text
    font_size = 90
    font_family = $font
    position = -130, -100
    halign = right
    valign = top
    shadow_passes = 2
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -130, -250
    halign = right
    valign = top
    shadow_passes = 2
}

# KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT
    color = $text
    font_size = 20
    font_family = $font
    rotate = 0 # degrees, counter-clockwise

    position = -130, -310
    halign = right
    valign = top
    shadow_passes = 2
}

# INPUT FIELD
input-field {
    monitor =
    size = 400, 70
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha"><i>$USER</i></span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -185
    halign = center
    valign = center
    shadow_passes = 2
}
