format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$jobs\
$character"""

add_newline = false

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"
read_only = ""
style = "bold cyan"

[git_branch]
format = '[\($branch\)]($style) ' 
