## name: Dracula (modified to use konsole breeze colors, which are nicer for the eyes)
## author: Keegan Carruthers-Smith
## license: MIT
## upstream: https://raw.githubusercontent.com/dracula/kitty/master/dracula.conf
wayland_titlebar_color #2E3440 

foreground            #f8f8f2
background            #232627
selection_foreground  none 
selection_background  #4E5051
url_color #8be9fd
color0  #21222c
color1  #C0392B
color2  #11D116
color3  #FDBC4B
color4  #1D99F3
color5  #8E44AD
color6  #16A085
color7  #FFFFFF
cursor            #f8f8f2
cursor_text_color background
active_tab_foreground   #282a36
active_tab_background   #f8f8f2
inactive_tab_foreground #282a36
inactive_tab_background #6272a4
mark1_foreground #282a36
mark1_background #ff5555
