## name: Dracula (modified to use konsole breeze colors, which are nicer for the eyes)
## author: Keegan Carruthers-Smith
## license: MIT
## upstream: https://raw.githubusercontent.com/dracula/kitty/master/dracula.conf

foreground            #f8f8f2
background            #232627
selection_foreground  none 
selection_background  #4E5051
url_color #8be9fd
color0  #21222c
color8  #6272a4
color1  #C0392B
color9  #ff6e6e
color2  #11D116
color10 #69ff94
color3  #FDBC4B
color11 #ffffa5
color4  #1D99F3
color12 #d6acff
color5  #8E44AD
color13 #ff92df
color6  #16A085
color14 #a4ffff
color7  #FFFFFF
color15 #ffffff
cursor            #f8f8f2
cursor_text_color background
active_tab_foreground   #282a36
active_tab_background   #f8f8f2
inactive_tab_foreground #282a36
inactive_tab_background #6272a4
mark1_foreground #282a36
mark1_background #ff5555
