MBTN_LEFT       cycle pause
MBTN_LEFT_DBL   cycle fullscreen
MBTN_RIGHT      ignore

RIGHT           seek  15                          
LEFT            seek -15                          
Shift+RIGHT     seek  5                         
Shift+LEFT      seek -5                          
. frame-step                           
, frame-back-step                      

f               cycle fullscreen
ESC             set fullscreen no
space           cycle pause
o               show-progress
i script-binding stats/display-stats-toggle 
l ab-loop 

DEL script-binding osc/visibility      
ctrl+h cycle-values hwdec "no" "auto-safe" 
