keep-open=yes
screenshot-directory=~/Pictures/

# disable all bindings
no-input-default-bindings

# remove progress bar
script-opts=osc-visibility=auto

# disable window size ratio
no-keepaspect-window
geometry=1000x600

# WARNING: may cause problems #
hwdec=auto-safe
