keep-open=yes
screenshot-directory=~/Pictures/

# disable all bindings
no-input-default-bindings

# remove progress bar
script-opts=osc-visibility=always

# disable window size ratio
no-keepaspect-window

# WARNING: may cause problems #
hwdec=auto-safe
