keep-open=yes
screenshot-directory=~/Pictures/

# disable all bindings
no-input-default-bindings

# force progress bar (solves gnome ssd problem)
script-opts=osc-visibility=always

# WARNING: may cause problems #
hwdec=auto-safe
