# global submap bindings
bind = super, escape, submap,  reset
bind = super, f1, submap,  clean

# submap with no bindings
submap = clean
bind = super, escape, submap,  reset
bind = super, f1, submap,  clean
submap = reset
