# change focused or move window
binde = super, left, movefocus, l
binde = super, right, movefocus, r
binde = super, up, movefocus, u
binde = super, down, movefocus, d
binde = super shift, left, movewindow, l
binde = super shift, right, movewindow, r
binde = super shift, up, movewindow, u
binde = super shift, down, movewindow, d

# change focused or move workspace
bind = super, 1, workspace, 1
bind = super, 2, workspace, 2
bind = super, 3, workspace, 3
bind = super, 4, workspace, 4
bind = super, 5, workspace, 5
bind = super, 6, workspace, 6
bind = super, 7, workspace, 7
bind = super, 8, workspace, 8
bind = super, 9, workspace, 9
bind = super shift, 1, movetoworkspace, 1
bind = super shift, 2, movetoworkspace, 2
bind = super shift, 3, movetoworkspace, 3
bind = super shift, 4, movetoworkspace, 4
bind = super shift, 5, movetoworkspace, 5
bind = super shift, 6, movetoworkspace, 6
bind = super shift, 7, movetoworkspace, 7
bind = super shift, 8, movetoworkspace, 8
bind = super shift, 9, movetoworkspace, 9
bind = super alt, 1, movetoworkspacesilent, 1
bind = super alt, 2, movetoworkspacesilent, 2
bind = super alt, 3, movetoworkspacesilent, 3
bind = super alt, 4, movetoworkspacesilent, 4
bind = super alt, 5, movetoworkspacesilent, 5
bind = super alt, 6, movetoworkspacesilent, 6
bind = super alt, 7, movetoworkspacesilent, 7
bind = super alt, 8, movetoworkspacesilent, 8
bind = super alt, 9, movetoworkspacesilent, 9
bind = super, o, workspace, empty
bind = super shift, o, movetoworkspace, empty
bind = super alt, o, movetoworkspacesilent, empty
bind = super, s, workspace, 100
bind = super shift, s, movetoworkspace, 100
bind = super alt, s, movetoworkspacesilent, 100
bind = super, period, exec, hyprctl dispatch workspace "$({ hyprctl activeworkspace -j | jq '.id'; hyprctl clients -j | jq 'sort_by(.focusHistoryID) | .[].workspace.id'; } | uniq | head -2 | tail -1)"
bind = super shift, period, focusurgentorlast
binde = super alt, left, workspace, e-1
binde = super alt, right, workspace, e+1

# various bindings
bind = super, q, killactive 
bind = super shift, q, exec, kill "$( hyprctl activewindow -j | jq .pid )" 
bind = super, f, fullscreen, 1
bind = super, g, togglesplit
bind = super, v, togglefloating
bindm = super, mouse:272, movewindow
bindm = super, mouse:273, resizewindow
bind = super, i, exec, pkill -SIGUSR1 waybar || waybar
bind = super shift, i, exec, pkill -SIGUSR2 waybar || waybar

# launch apps 
bind = super, t, exec, konsole
bind = super, b, exec, firefox
bind = super, e, exec, pgrep wofi || wofi -aiIS drun

# screenshot 
bind = shift ,Print, exec, pgrep slurp || grim
bind = ,Print, exec, pgrep slurp || grim -g "$(slurp)" 

# fn keys 
bindel=, XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel=, XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel=, XF86MonBrightnessDown, exec, brightnessctl set 5%- -n
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioPrev, exec, playerctl previous
bindl = ,XF86AudioNext, exec, playerctl next

# lock screen 
bind = super, l, exec, hyprlock
bindl= ,switch:Lid Switch, exec, hyprlock
