source = lib/*.conf
source = lib/multi/*.conf

# extra rules
windowrulev2 = workspace 1, class:^org\.kde\.konsole$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 2, class:^org\.mozilla\.firefox$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 3, class:^org\.kde\.okular$, onworkspace: s[false] r[1-10]
windowrulev2 = workspace 11, class:^org\.kde\.konsole$, onworkspace: s[false] r[11-20]
windowrulev2 = workspace 12, class:^org\.mozilla\.firefox$, onworkspace: s[false] r[11-20]
windowrulev2 = workspace 13, class:^org\.kde\.okular$, onworkspace: s[false] r[11-20]

# extra startup
exec-once = ~/.config/hypr/configs/lib/multi/scripts/events.sh

# overwrite variables
gestures:workspace_swipe = off

