source = lib/*.conf
source = lib/simple/*.conf

# extra rules 
windowrulev2 = workspace 1, class:^org\.kde\.konsole$, onworkspace: s[false] 
windowrulev2 = workspace 2, class:^org\.mozilla\.firefox$, onworkspace: s[false] 
windowrulev2 = workspace 3, class:^org\.kde\.okular$, onworkspace: s[false] 
