# command to execute after launching Hyprland
exec-once = waybar
exec-once = gammastep -O 4000
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Breeze'
exec-once = powerprofilesctl set balanced

